on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 */6 * * *' # every 6 hours

name: Update plugin_details.md

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
        -   name: Setup Nushell
            uses: hustcer/setup-nu@v3.8
            with:
              version: 0.87.0
        -   uses: actions/checkout@v2
        -   name: Update plugin list
            shell: nu {0}
            run: |
                nu -c '
                let output = "plugin_details.md";
                let config = "config.yaml";

                use action.nu plugin-list create-table;
                
                open $config | create-table | to md | save $output -f;
                $"\n\nlast update at `(date now | format date `%Y-%m-%d %H:%M:%S %Z`)`\n" | save --append $output;
                '
                
        -   uses: EndBug/add-and-commit@v9 
            with:
                add: plugin_details.md # Only commit+push the output file 
                author_name: GitHub-Action
